const dummyReviews = [
  { name: "Ahmed", comment: "Great product and quality!", rating: 5 },
  { name: "Sara", comment: "Exactly what I needed. Perfect fit!", rating: 4 },
  { name: "Youssef", comment: "Average quality. Not bad.", rating: 3 },
  { name: "Mona", comment: "Fast delivery and nice packaging!", rating: 4 },
  { name: "Omar", comment: "Didn't meet my expectations.", rating: 2 },
  { name: "Laila", comment: "Amazing value for money.", rating: 5 },
  { name: "Khaled", comment: "Works just fine, satisfied.", rating: 4 },
  { name: "Nour", comment: "Could be better in quality.", rating: 3 },
  { name: "Hassan", comment: "Great for everyday use!", rating: 5 },
  { name: "Farah", comment: "Too expensive for what it offers.", rating: 2 },
  { name: "Ali", comment: "Highly recommended!", rating: 5 },
  { name: "Reem", comment: "Nice but a bit small in size.", rating: 3 },
  { name: "Walid", comment: "Exactly as described.", rating: 4 },
  { name: "Salma", comment: "Stylish and comfortable!", rating: 5 },
  { name: "Hany", comment: "Low quality material.", rating: 2 },
  { name: "Dina", comment: "Would buy again!", rating: 5 },
  { name: "Tarek", comment: "Not what I expected.", rating: 2 },
  { name: "Mariam", comment: "Beautiful design!", rating: 4 },
  { name: "Mostafa", comment: "Fast shipping and good price.", rating: 4 },
  { name: "Nada", comment: "Not durable at all.", rating: 1 },
  { name: "Ramy", comment: "Exceeded expectations!", rating: 5 },
  { name: "Esraa", comment: "Good quality for the price.", rating: 4 },
  { name: "Mohamed", comment: "Too tight, even for my size.", rating: 2 },
  { name: "Heba", comment: "Loved it so much!", rating: 5 },
  { name: "Abdullah", comment: "Looks different from the photo.", rating: 2 },
  { name: "Yara", comment: "Very soft and comfy.", rating: 5 },
  { name: "Bassel", comment: "Disappointed with the material.", rating: 2 },
  { name: "Leila", comment: "Great value, stylish too.", rating: 4 },
  { name: "Ziad", comment: "Color faded after one wash.", rating: 1 },
  { name: "Rania", comment: "Lightweight and breathable.", rating: 4 }
];

export default dummyReviews;
